OptimalTest/Models/ErrorViewModel.cs
using System;

namespace OptimalTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OptimalTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using OptimalTest.Models;

namespace OptimalTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OptimalTest/Controllers/ProdutosController.cs
using Domain;
using Infrastructure.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OptimalTest.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly IProdutoRepository _produtoRepository;
        private readonly ITipoRepository _tipoRepository;

        public ProdutosController(IProdutoRepository produtoRepository, ITipoRepository tipoRepository){
            _produtoRepository = produtoRepository;
            _tipoRepository = tipoRepository;
        }


        // GET: ProdutosController
        public async Task<ActionResult> Index()
        {
            var produtos = await _produtoRepository.GetAllProdutosWithTipoAsync();
            return View(produtos);
        }

        // GET: ProdutosController/Details/5
        public async Task<ActionResult> Details(int id){
            var produto = await _produtoRepository.GetProdutoByIdAsync(id);
            return View(produto);
        }

        // GET: ProdutosController/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.Tipos = new SelectList((await _tipoRepository.ListAll()), "id", "descricao");
            return View();
        }

        // POST: ProdutosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Produto produto, string TipoProduto)
        {
            try
            {
                if(ModelState.IsValid){
                    var tipoProduto = await _tipoRepository.GetTipoById(int.Parse(TipoProduto)); 

                    produto.TipoProduto = tipoProduto;
                    await _produtoRepository.Add(produto);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProdutosController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            
            var produto = await _produtoRepository.GetProdutoByIdAsync(id);
            ViewBag.Tipos = new SelectList(await _tipoRepository.ListAll(), "id", "descricao", produto.TipoProduto);
            return View(produto);
        }

        // POST: ProdutosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Produto produto, string TipoProduto)
        {                       
            try
            {
                if(ModelState.IsValid){
                    var tipoProduto = await _tipoRepository.GetTipoById(int.Parse(TipoProduto)); 

                    produto.TipoProduto = tipoProduto;
                    await _produtoRepository.Update(produto);

                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProdutosController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var produto = await _produtoRepository.GetProdutoByIdAsync(id);
            return View(produto);
        }

        // POST: ProdutosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Produto produto)
        {
            try
            {
                await _produtoRepository.Delete(produto);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

OptimalTest/Controllers/TiposController.cs
using Domain;
using Infrastructure.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OptimalTest.Controllers
{
    public class TiposController : Controller
    {
        private readonly ITipoRepository _tipoRepository;
        public TiposController(ITipoRepository tipoRepository){
            _tipoRepository = tipoRepository;
        }

        // GET: TiposController
        public async Task<ActionResult> Index()
        {
            var tipos = await _tipoRepository.ListAll();
            return View(tipos);
        }

        // GET: TiposController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var tipo = await _tipoRepository.GetTipoById(id);
            return View(tipo);
        }

        // GET: TiposController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TiposController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TipoProduto tipo)
        {
            try
            {
                if(ModelState.IsValid){
                    await _tipoRepository.Add(tipo);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TiposController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var tipo = await _tipoRepository.GetTipoById(id);
            return View(tipo);
        }

        // POST: TiposController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(TipoProduto tipo)
        {
            try
            {   
                if(ModelState.IsValid)
                    await _tipoRepository.Update(tipo);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: TiposController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var tipo = await _tipoRepository.GetTipoById(id);
            return View(tipo);
        }

        // POST: TiposController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(TipoProduto tipo)
        {
            try
            {
                await _tipoRepository.Delete(tipo);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

OptimalTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo!</h1>
    <p>Teste OptimalDiscovery </p>
</div>

OptimalTest/Views/Produtos/Create.cshtml
@model Domain.Produto

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastro</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="codigo" class="control-label">Código</label>
                <input asp-for="codigo" class="form-control" />
                <span asp-validation-for="codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descricao" class="control-label">Descrição</label>
                <input asp-for="descricao" class="form-control" />
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoProduto" class="control-label">Tipo do Produto</label>
                <select asp-for="TipoProduto" asp-items="ViewBag.Tipos" class="form-control"></select>
                <span asp-validation-for="TipoProduto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantidade" class="control-label">Quantidade</label>
                <input asp-for="quantidade" class="form-control" />
                <span asp-validation-for="quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="preco" class="control-label">Preço</label>
                <input asp-for="preco" class="form-control" />
                <span asp-validation-for="preco" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OptimalTest/Views/Produtos/Delete.cshtml
@model Domain.Produto

@{
    ViewData["Title"] = "Deletar";
}

<h1>Deletar</h1>

<h3>Tem certeza?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Código
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.codigo)
        </dd>
        <dt class="col-sm-2">
            Descrição
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>
        <dt class="col-sm-2">
            Tipo do Produto
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoProduto.descricao)
        </dd>
        <dt class="col-sm-2">
            Quantidade
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.quantidade)
        </dd>
        <dt class="col-sm-2">
            Preço
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.preco)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

OptimalTest/Views/Produtos/Details.cshtml
@model Domain.Produto

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Código
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.codigo)
        </dd>

        <dt class="col-sm-2">
            Descrição
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>

        <dt class="col-sm-2">
            Tipo do Produto
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoProduto.descricao)
        </dd>

        <dt class="col-sm-2">
            Quantidade
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.quantidade)
        </dd>
        
        <dt class="col-sm-2">
            Preço
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.preco)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Editar</a> |
    <a asp-action="Index">Voltar a lista</a>
</div>

OptimalTest/Views/Produtos/Edit.cshtml
@model Domain.Produto

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="codigo" class="control-label">Código</label>
                <input asp-for="codigo" class="form-control" />
                <span asp-validation-for="codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descricao" class="control-label">Descrição</label>
                <input asp-for="descricao" class="form-control" />
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoProduto" class="control-label">Tipo de Produto</label>
                <select asp-for="TipoProduto" asp-items="ViewBag.Tipos" class="form-control"></select>
                <span asp-validation-for="TipoProduto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantidade" class="control-label">Quantidade</label>
                <input asp-for="quantidade" class="form-control" />
                <span asp-validation-for="quantidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="preco" class="control-label">Preço</label>
                <input asp-for="preco" class="form-control" />
                <span asp-validation-for="preco" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <input type="submit" value="Salvar Edição" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OptimalTest/Views/Produtos/Index.cshtml
@model IEnumerable<Domain.Produto>

@{
    ViewData["Title"] = "Lista de Produtos";
}

<h1>Lista de Produtos</h1>

<div class="busca">
   <input type="search" id="pesquisa"><button type="button" onclick="filtrar()">Filtrar</button>
</div>

<p>
    <a asp-action="Create">Cadastrar novo Produto</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Código
            </th>
            <th>
                Descrição
            </th>
            <th>
                Tipo do Produto
            </th>           
            <th>
                Quantidade
            </th>
            <th>
                Preço
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoProduto.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.preco)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>

OptimalTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OptimalTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Teste Optimal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tipos" asp-action="Index">Tipos de Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OptimalTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OptimalTest/Views/Tipos/Create.cshtml
@model Domain.TipoProduto

@{
    ViewData["Title"] = "Cadastro";
}

<h1>Cadastro de Tipo</h1>

<h4>Tipos de Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Tipos">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="descricao" class="control-label">Descrição</label>
                <input asp-for="descricao" class="form-control" />
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OptimalTest/Views/Tipos/Delete.cshtml
@model Domain.TipoProduto

@{
    ViewData["Title"] = "Deletar";
}

<h1>Deletar</h1>

<h3>Tem certeza?</h3>
<div>
    <h4>Tipos de Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Descrição
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id"/>
        <input type="submit" value="Deletar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

OptimalTest/Views/Tipos/Details.cshtml
@model Domain.TipoProduto

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Tipos de Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Descrição
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Editar</a> |
    <a asp-action="Index">Voltar a lista</a>
</div>

OptimalTest/Views/Tipos/Edit.cshtml
@model Domain.TipoProduto

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Tipos de Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="descricao" class="control-label">Descrição</label>
                <input asp-for="descricao" class="form-control" />
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar Edição" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

OptimalTest/Views/Tipos/Index.cshtml
@model IEnumerable<Domain.TipoProduto>

@{
    ViewData["Title"] = "Lista de Tipos";
}

<h1>Lista de Tipos</h1>

<p>
    <a asp-action="Create">Cadastrar novo Tipo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Descrição
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Deletar</a>
            </td>
        </tr>
}
    </tbody>
</table>